services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_langmem
    ports:
      - "6335:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis:7-alpine
    container_name: redis_langmem
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  qdrant_data:
  redis_data: